open-feature/js-sdk-contrib

- package-lock.json
- package.json
We are using an old version of the `node-sdk`, I needed the error but they were not available.
> Bump node-sdk to 0.0.1-alpha.48

- libs/providers/go-feature-flag/package.json
Since version `0.0.1` is not released yet I had some errors when trying to build a new project using the provider.
```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test-nodesdk@1.0.0
npm ERR! Found: @openfeature/nodejs-sdk@undefined
npm ERR! node_modules/@openfeature/nodejs-sdk
npm ERR!   @openfeature/nodejs-sdk@"^0.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @openfeature/nodejs-sdk@"^0.0.1" from @openfeature/go-feature-flag-provider@0.1.2
npm ERR! node_modules/@openfeature/go-feature-flag-provider
npm ERR!   @openfeature/go-feature-flag-provider@"^0.1.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, …
```
> fix: Peer dependencies error

- libs/providers/flagd/README.md
- libs/providers/flagd/src/lib/flagd-provider.spec.ts
- libs/providers/flagd/src/lib/flagd-provider.ts
- libs/providers/flagd/src/lib/service/grpc/service.ts
This PR adds support for Unix sockets when using gRPC.
I did notice a few items that should be discussed and addressed in a future PR.
> feat: add Unix socket support

- libs/hooks/README.md
- libs/providers/README.md
In one of the [spec prs](https://github.com/open-feature/spec/pull/118) docs were restructured, but the links in this repository were not updated to reflect the changes. This PR simply updates the broken links here
N/A
N/A
N/A
N/A
> docs: fixed broken links in docs

- libs/hooks/open-telemetry/package.json
- libs/hooks/open-telemetry/project.json
- libs/providers/flagd-web/package.json
- libs/providers/flagd/package.json
- libs/providers/flagd/project.json
- libs/providers/go-feature-flag/package.json
- libs/providers/go-feature-flag/project.json
- tools/generators/open-feature/index.ts
Fixes: https://github.com/open-feature/js-sdk-contrib/issues/198
This _seems_ to be the result of a breaking change in the nx `@nrwl/web:rollup` executor, which previously added an exports statement. I have moved to `@nrwl/rollup:rollup` with the `tsc` compiler, which generates the exports correctly and also fixes some [inappropriate polyfills](https://github.com/nrwl/nx/issues/10304) the `@nrwl/web:rollup` executor was adding.
> fix: fix ESM and web polyfills issue

- assets/package.json
- libs/hooks/open-telemetry/project.json
- libs/providers/flagd-web/project.json
- libs/providers/flagd/project.json
- libs/providers/go-feature-flag/project.json
- tools/generators/open-feature/index.ts
Fixes an issue with imports in ES module projects. Specifically, in some TS configurations, compilation would fail because TS esm support requires file extensions on all imports. Though our code is bundled, our declaration files are not, and they are also subject to this requirement. To avoid having to add `.js` extensions in our rendered type files, this adds a package.json with `type: commonjs` only in the type file roots, making them behave as commonjs modules, (which don't require file extensions in imports).
I attempted first to bundle all our types into a single d.ts (to avoid imports entirely), but was unable to find a decent solution to that.
Fixes: https://github.com/open-feature/js-sdk-contrib/issues/198
I've tested this fix with the example repo in the linked issue, as well as …
> fix: module issues with types

- .release-please-manifest.json
- libs/providers/in-memory/.eslintrc.json
- libs/providers/in-memory/README.md
- libs/providers/in-memory/babel.config.json
- libs/providers/in-memory/jest.config.ts
- libs/providers/in-memory/package.json
- libs/providers/in-memory/project.json
- libs/providers/in-memory/src/index.ts
- libs/providers/in-memory/src/lib/flag-configuration.ts
- libs/providers/in-memory/src/lib/in-memory-provider.spec.ts
- libs/providers/in-memory/src/lib/in-memory-provider.ts
- libs/providers/in-memory/tsconfig.json
- libs/providers/in-memory/tsconfig.lib.json
- libs/providers/in-memory/tsconfig.spec.json
- package.json
- release-please-config.json
- tsconfig.base.json
adds a super simple in-memory provider, for use in automated tests, and for demos.
> feat: add in memory provider

- libs/providers/go-feature-flag/src/lib/errors/unauthorized.ts
- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.spec.ts
- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.ts
- libs/providers/go-feature-flag/src/lib/model.ts
Since version `v1.7.0` GO Feature Flag relay proxy support an authorization key.
This PR makes it possible to send this API Key to the proxy.
Fixes https://github.com/thomaspoignant/go-feature-flag/issues/666
> feat: Support apiKey for GO Feature Flag relay proxy v1.7.0

- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.spec.ts
- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.ts
This PR fixes an issue on the way to add the authentication header to Axios.
The previous way of doing it was invalid.
Fixing the associated test also because it should have break the tests.
> fix: go-feature-flag provider add authentication header

- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.ts
I am struggling here and adding more bugs at every commit 🤦 
This one should be the good one 🤞
I was using `this.apiKey` instead of `options.apiKey`.
> fix: go-feature-flag provider this.apiKey is undefined

- libs/hooks/open-telemetry/project.json
- libs/providers/env-var/project.json
- libs/providers/go-feature-flag/project.json
- libs/providers/in-memory/project.json
Some of the publish commands were using a "workspace executor", instead of an nx one.
> chore: correct publish executor

- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.spec.ts
- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.ts
- Return `CACHED` as a reason when using the cache in the provider.
> feat: Return CACHED reason when using cache

- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.ts
- package-lock.json
- package.json
- use `copy-anything` for deepClone to be compatible with nodeJS before v17
Fixes #428
> fix: use copy-anything for deepClone to be compatible with nodeJS before v17

- .github/workflows/ci.yml
Fixes: https://github.com/open-feature/js-sdk-contrib/issues/430
> chore: add node version matrix to ci

- .github/workflows/ci.yml
I neglected to actually USE the different versions :grimacing: 
Fixes: https://github.com/open-feature/js-sdk-contrib/issues/430
(for real this time)
> chore: use node-version

- .github/component_owners.yml
- .github/workflows/component-owners.yml
Adds component_owners for all components
> chore: use component_owners

- libs/hooks/open-telemetry/README.md
- libs/hooks/open-telemetry/src/lib/open-telemetry-hook.ts
Giving some warning and redirecting people to the new package.
See discussion [here](https://github.com/open-feature/js-sdk-contrib/issues/447#issuecomment-1625550744).
> fix: deprecate otel hook

- .release-please-manifest.json
- libs/hooks/open-telemetry/README.md
- libs/hooks/open-telemetry/package.json
- libs/hooks/open-telemetry/src/index.ts
- libs/hooks/open-telemetry/src/lib/constants.ts
- libs/hooks/open-telemetry/src/lib/metrics/index.ts
- libs/hooks/open-telemetry/src/lib/metrics/metrics-hook.spec.ts
- libs/hooks/open-telemetry/src/lib/metrics/metrics-hook.ts
- libs/hooks/open-telemetry/src/lib/traces/index.ts
- libs/hooks/open-telemetry/src/lib/traces/tracing-hook.spec.ts
- libs/hooks/open-telemetry/src/lib/traces/tracing-hook.ts
- package-lock.json
- package.json
- release-please-config.json
* add metrics hook
* rename open-telemetry hook to tracing hook
----
We should also merge [this](https://github.com/open-feature/js-sdk-contrib/pull/449) first, to provide a deprecation warning for the old package/hook.
Fixes: https://github.com/open-feature/js-sdk-contrib/issues/447
> feat!: add metrics hook

- libs/providers/flagd/README.md
- libs/providers/flagd/package.json
- libs/providers/flagd/src/lib/flagd-provider.spec.ts
- libs/providers/flagd/src/lib/flagd-provider.ts
- libs/providers/flagd/src/lib/service/grpc/service.ts
- libs/providers/flagd/src/lib/service/service.ts
- package-lock.json
- package.json
This PR:
- absorbs changes related to updating our proto generation plugin
- adds change events when change messages received from flagd
- adds shutdown
:warning: depends on https://github.com/open-feature/schemas/pull/99 (must be merged first). Will keep this as draft until then.
Fixes: https://github.com/open-feature/js-sdk-contrib/issues/382
> feat!: events, init, shutdown

- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.spec.ts
- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.ts
- Implement ProviderStatus
Fixes #489
> fix: [GO Feature Flag server] Implement ProviderStatus

- libs/providers/flagd-web/src/lib/flagd-web-provider.spec.ts
- libs/providers/flagd-web/src/lib/flagd-web-provider.ts
- package-lock.json
- package.json
Adds status to flagd web, adds provider scoping to unit tests to reduce interference.
Fixes: https://github.com/open-feature/js-sdk-contrib/issues/490
> fix: add status to flagd web

- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.spec.ts
- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.ts
- Return an error if we try to evaluate before the provider is ready.
- Rewrite the tests to use the SDK and not test only the provider.
> fix: [GO Feature Flag server] handle PROVIDER_NOT_READY from the spec

- libs/providers/flagd-web/project.json
- libs/providers/flagd/project.json
This fixes a race condition in the build/test/lint which is caused by simultaneously and recursively pulling submodules.
This fix is to just pull the relevant submodule per component.
> chore: fix submodule race

- libs/hooks/open-telemetry/README.md
- libs/hooks/open-telemetry/src/lib/conventions.ts
- libs/hooks/open-telemetry/src/lib/metrics/metrics-hook.spec.ts
- libs/hooks/open-telemetry/src/lib/metrics/metrics-hook.ts
- libs/hooks/open-telemetry/src/lib/otel-hook.ts
- libs/hooks/open-telemetry/src/lib/traces/tracing-hook.spec.ts
- libs/hooks/open-telemetry/src/lib/traces/tracing-hook.ts
This PR: 
- adds custom attrs to the `TracesHook`, similarly to what we have in the `MetricsHook`
- adds tests, and reformats tests
- adds js-doc
> feat: add custom attrs to traces

- libs/providers/flagd/src/lib/service/grpc/grpc-service.ts
Since node 15, unhandled promise rejections throw.
Our retry logic in our timeout doesn't require awaiting, but in 15+ we at least need to add a handler to prevent this out-of-chain rejection from killing the process.
> fix: unhandled rejection on init

- libs/providers/go-feature-flag/src/lib/data-collector-hook.ts
- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.spec.ts
- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.ts
- libs/providers/go-feature-flag/src/lib/model.ts
- Move the data collector call into a hook
- Change the cache key with the hash of the entire context.
> chore: GO Feature Flag move datacollector to hook + change cache key

- renovate.json
-  Disable NX update via Renovate
NX upgrades require a migration process that can't easily be handled by renovate.
https://nx.dev/core-features/automate-updating-dependencies
> chore: Disable NX update via Renovate

- libs/providers/go-feature-flag-web/src/lib/go-feature-flag-web-provider.ts
- allow `wss` connection to the WebSocket endpoint.
Fixes #624
> fix: GOFF Authorize connecting in a secure way to the websocket

- libs/shared/flagd-core/src/lib/flagd-core.spec.ts
- add target value casting test
Confirms that the example provided in the flagd docs works as expected.
https://flagd.dev/reference/flag-definitions/#flag-properties
> test: add target value casting test

- libs/shared/flagd-core/src/lib/flagd-core.spec.ts
- libs/shared/flagd-core/src/lib/flagd-core.ts
- fixes an issue where an empty targeting rule would be stringified and used as the variant.
I've also updated the Gherkin test suite to handle this scenario.
https://github.com/open-feature/flagd-testbed/pull/88
> fix: treat empty targeting rules as static

- libs/providers/flagd-web/src/e2e/jest.config.ts
Absorbs the change here to fix an issue with TSC errors in shipped output. See [here](https://github.com/open-feature/flagd-schemas/pull/118) for submodule change.
Fixes: https://github.com/open-feature/js-sdk-contrib/issues/688
> fix: tsc issue with flagd-web proto output

- libs/shared/flagd-core/src/lib/feature-flag.ts
- libs/shared/flagd-core/src/lib/flagd-core.ts
- libs/shared/flagd-core/src/lib/storage.spec.ts
- libs/shared/flagd-core/src/lib/storage.ts
- adds an update config method that returns all affected flag keys
- adds hash to internal feature flag class
> feat(flagd-core): add update config support, returns changed keys

- .github/component_owners.yml
- .release-please-manifest.json
- libs/providers/flipt/.eslintrc.json
- libs/providers/flipt/README.md
- libs/providers/flipt/babel.config.json
- libs/providers/flipt/jest.config.ts
- libs/providers/flipt/package-lock.json
- libs/providers/flipt/package.json
- libs/providers/flipt/project.json
- libs/providers/flipt/src/index.ts
- libs/providers/flipt/src/lib/context-transformer.spec.ts
- libs/providers/flipt/src/lib/context-transformer.ts
- libs/providers/flipt/src/lib/flipt-provider.spec.ts
- libs/providers/flipt/src/lib/flipt-provider.ts
- libs/providers/flipt/tsconfig.json
- libs/providers/flipt/tsconfig.lib.json
- libs/providers/flipt/tsconfig.spec.json
- package-lock.json
- package.json
- release-please-config.json
- tsconfig.base.json
Add Flipt openfeature provider.
- adds this new feature
> feat(flipt): Add Flipt provider in openfeature-js

- libs/shared/flagd-core/src/lib/flagd-core.spec.ts
- libs/shared/flagd-core/src/lib/flagd-core.ts
- update disabled behavior to match spec 
https://github.com/open-feature/flagd/issues/1035
Disabled flags will now behave as if they don't exist. This is consistent with the rest of the flagd ecosystem.
> fix: update disabled behavior to match spec 

- libs/shared/flagd-core/src/lib/flagd-core.spec.ts
- libs/shared/flagd-core/src/lib/flagd-core.ts
- fixes falsy boolean shorthand logic
Prior to the change, the default variant would be returned when the logic was falsy. After the change, the "false" variant is used.
> fix: falsy boolean shorthand logic

- .github/workflows/ci.yml
- libs/providers/flagd-web/src/lib/flagd-web-provider.spec.ts
- libs/providers/flagd-web/src/lib/flagd-web-provider.ts
- libs/providers/flagd/src/e2e/step-definitions/flagd.spec.ts
- libs/providers/flagd/src/lib/flagd-provider.spec.ts
- libs/providers/flagd/src/lib/service/grpc/grpc-service.ts
- libs/providers/flagd/src/lib/service/in-process/grpc/grpc-fetch.spec.ts
- libs/providers/flagd/src/lib/service/in-process/grpc/grpc-fetch.ts
* use new evaluation.proto
* use new sync.proto
* requires usage of flagd v0.7.3+
Resolves: https://github.com/open-feature/js-sdk-contrib/issues/743
> feat!: use new eval/sync protos (requires flagd v0.7.3+) 

- libs/providers/flagd/src/e2e/constants.ts
- libs/providers/flagd/src/e2e/setup-in-process-provider.ts
- libs/providers/flagd/src/e2e/setup-rpc-provider.ts
- libs/providers/flagd/src/e2e/step-definitions/evaluation.spec.ts
- libs/providers/flagd/src/e2e/step-definitions/flagd-json-evaluator.spec.ts
- libs/providers/flagd/src/e2e/step-definitions/flagd-reconnect.unstable.spec.ts
- libs/providers/flagd/src/e2e/step-definitions/flagd.spec.ts
- libs/providers/flagd/src/lib/service/in-process/grpc/grpc-fetch.ts
- libs/shared/flagd-core/src/lib/flagd-core.spec.ts
- libs/shared/flagd-core/src/lib/flagd-core.ts
* fixes an unhandled error if sync source not available at startup
* throws on invalid targeting rules as per flagd spec
* adds additional e2e tests
---
Implements the latest e2e tests, including those added [here](https://github.com/open-feature/flagd-testbed/pull/85). Here we decided that invalid targeting should throw, which required a small change in core.
I also found a [bug](https://github.com/open-feature/js-sdk-contrib/pull/767/files#r1488560278) on the in-process provider where there's an unhandled exception in startup.
> fix: init in-process error, throw on invalid rules

- libs/providers/config-cat/README.md
- libs/providers/config-cat/package.json
- libs/providers/config-cat/src/lib/config-cat-provider.spec.ts
- libs/providers/config-cat/src/lib/config-cat-provider.ts
- libs/providers/config-cat/src/lib/context-transformer.ts
- package-lock.json
- package.json
The `conficat-js` package that the ConfigCat provider is based on is for browser applications only as it uses `XMLHttpRequest` under the hood. However, the provider might be used in server applications (like it was attempted in a Node.js application [here](https://www.linkedin.com/video/event/urn:li:ugcPost:7173464062830239744), at around 2:00:00).
For multiplatform scenarios, ConfigCat provides [the `conficat-js-ssr` package](https://configcat.com/docs/sdk-reference/js-ssr/) (that uses Axios under the hood). This provider should use that instead of `conficat-js` to provide a more extensive support for various JS platforms.
This PR also fixes another serious shortcoming of the provider: currently it cannot evaluate feature flags without setting `targetingKey` in the evaluation context. …
> fix!: Allow ConfigCat provider to be used in server applications

- libs/providers/config-cat/src/lib/config-cat-provider.spec.ts
- package-lock.json
- package.json
A [recent change](https://github.com/open-feature/js-sdk-contrib/pull/825) updated this configcat dep, which brought in a breaking change to out testing (noted in-line).
This PR locks the dep to the point-version so prevent test regressions.
We should probably find a better long-term solution.
> chore: lock configcat dep

- libs/providers/config-cat/src/lib/config-cat-provider.spec.ts
- package-lock.json
- package.json
Removes the `IEventEmitter` import from configcat-common.
This reduces the risk of breaking the tests because of the removal of this type (export).
It tackles the same problem as #827. 
As there is currently no option to access the internal event emitter or provide it directly, the assumption getting the event emitter from the private options can not be removed.
https://github.com/open-feature/js-sdk-contrib/compare/fix/config-cat/remove-event-emitter-dep?expand=1#diff-ebd6f4363558237806382ec9b364f56831b69ad259c090f1981a4d56a7bb0bcdL43
> fix(config-cat): remove event emitter type import from config-cat

- libs/shared/ofrep-core/README.md
- libs/shared/ofrep-core/src/lib/api/errors.ts
- libs/shared/ofrep-core/src/lib/api/ofrep-api.spec.ts
- libs/shared/ofrep-core/src/test/handlers.ts
Implements parsing the retry after header in the `OFREPApiTooManyRequestsError ` as client and server provider need that information.
It can replace the current implementation in the web-provider. https://github.com/open-feature/js-sdk-contrib/pull/776#discussion_r1550601232
> feat(ofrep): parse Retry-After header in OFREPApiTooManyRequestsError

- libs/providers/config-cat/src/lib/config-cat-provider.ts
- libs/providers/flagd/src/lib/flagd-provider.ts
- libs/providers/flagd/src/lib/service/in-process/in-process-service.ts
- package-lock.json
Runs lint --fix on providers. Noticed the errors as a result of failed CI [here](https://github.com/open-feature/js-sdk-contrib/pull/836). Not sure how they crept through, perhaps an unpinned ESLint?
> chore: Lint Fix Providers

- libs/shared/ofrep-core/src/lib/api/errors.ts
Use the request time to compute the retry-after.
> fix: Use request time to compute the retry after

- libs/providers/flagsmith-client/project.json
https://github.com/open-feature/js-sdk-contrib/actions/runs/8606772734 failed, I believe this is due to the following paths not being updated when the provider was renamed from flagsmith to flagsmith-client. Sorry about that!
> fix: flagsmith project paths

- libs/providers/ofrep-web/package.json
- libs/providers/ofrep/package.json
Bumps OFREP core to ^0.1.2 to fix fetch error in browser.
> chore: bump ofrep-core to ^0.1.2

- libs/providers/flagd-web/src/lib/flagd-web-provider.spec.ts
- libs/providers/flagd-web/src/lib/flagd-web-provider.ts
- package-lock.json
- package.json
- migrate from bufbuild to connectrpc
Buf migrated to a dedicated `@connectrpc` org and updated their published packages according.
See the warning on the old package: https://www.npmjs.com/package/@bufbuild/connect-web
> chore: migrate from bufbuild to connectrpc

- libs/providers/flagd-web/src/lib/flagd-web-provider.ts
- libs/providers/flagd-web/src/lib/options.ts
This change enables passing interceptors to the flagd-web provider which can be leveraged to add extra headers to outgoing requests.
I'm working on bootstrapping a flagd deployment, and I have flagd behind a proxy that requires a session header. I didn't see an existing way to mutate requests.
> feat: Add interceptors to flagd options.

- .release-please-manifest.json
- libs/providers/growthbook-client/.eslintrc.json
- libs/providers/growthbook-client/README.md
- libs/providers/growthbook-client/babel.config.json
- libs/providers/growthbook-client/jest.config.ts
- libs/providers/growthbook-client/package-lock.json
- libs/providers/growthbook-client/package.json
- libs/providers/growthbook-client/project.json
- libs/providers/growthbook-client/src/index.ts
- libs/providers/growthbook-client/src/lib/growthbook-client-provider.spec.ts
- libs/providers/growthbook-client/src/lib/growthbook-client-provider.ts
- libs/providers/growthbook-client/src/lib/translate-result.spec.ts
- libs/providers/growthbook-client/src/lib/translate-result.ts
- libs/providers/growthbook-client/tsconfig.json
- libs/providers/growthbook-client/tsconfig.lib.json
- libs/providers/growthbook-client/tsconfig.spec.json
- package-lock.json
- package.json
- release-please-config.json
- tsconfig.base.json
- adds a new OpenFeature client provider for the GrowthBook JS SDK
Integrate OpenFeature into a test web app and set it up with this new GrowthBook provider. Ensure that GrowthBook flag evaluation works as expected using the OpenFeature API
[How to set up OpenFeature on a React app](https://openfeature.dev/docs/reference/technologies/client/web/react)
```
// Pass in gbContext the same way you would if you were instantiating GrowthBook directly
OpenFeature.setProvider(new GrowthbookClientProvider(gbContext))
```
> feat: Initial GrowthBook OpenFeature provider

- libs/providers/flagd/README.md
- libs/providers/flagd/src/lib/configuration.spec.ts
- libs/providers/flagd/src/lib/configuration.ts
closes: #936
The flagd provider defaults to RPC mode and the corresponding port (8013) using the [evaluation proto](https://buf.build/open-feature/flagd/docs/main:flagd.evaluation.v1). If the in-process resolver is selected, it operates in in-process mode using the [sync proto](https://buf.build/open-feature/flagd/docs/main:flagd.sync.v1), but still uses port 8013, instead of defaulting to the correct port (8015, for the sync proto).
We improve the configuration by defaulting to port 8015 if the in-process resolver is selected.
Fixes #936
> feat: Default port to 8015 if in-process resolver is used. #936

- libs/providers/multi-provider-web/.eslintrc.json
- libs/providers/multi-provider-web/README.md
- libs/providers/multi-provider-web/babel.config.json
- libs/providers/multi-provider-web/jest.config.ts
- libs/providers/multi-provider-web/package.json
- libs/providers/multi-provider-web/project.json
- libs/providers/multi-provider-web/src/index.ts
- libs/providers/multi-provider-web/src/lib/errors.ts
- libs/providers/multi-provider-web/src/lib/hook-executor.ts
- libs/providers/multi-provider-web/src/lib/multi-provider-web.spec.ts
- libs/providers/multi-provider-web/src/lib/multi-provider-web.ts
- libs/providers/multi-provider-web/src/lib/status-tracker.ts
- libs/providers/multi-provider-web/src/lib/strategies/BaseEvaluationStrategy.ts
- libs/providers/multi-provider-web/src/lib/strategies/ComparisonStrategy.ts
- libs/providers/multi-provider-web/src/lib/strategies/FirstMatchStrategy.ts
- libs/providers/multi-provider-web/src/lib/strategies/FirstSuccessfulStrategy.ts
- libs/providers/multi-provider-web/src/lib/strategies/index.ts
- libs/providers/multi-provider-web/src/lib/types.ts
- libs/providers/multi-provider-web/tsconfig.json
- libs/providers/multi-provider-web/tsconfig.lib.json
- libs/providers/multi-provider-web/tsconfig.spec.json
- adds a client-side JS implementation of the multi-provider concept documented [here]( https://taplytics.notion.site/OpenFeature-Multi-Provider-1014926cb35840b9b7b5756a71b9b76d)
- the implementation is almost identical to the Node implementation added in [this PR](https://github.com/open-feature/js-sdk-contrib/pull/916), the main differences are:
- the hooks and method are synchronous
- the before hook(s) do not modify the hookContext
`npx nx test providers-multi-provider-web`
> feat: client-side multi-provider implementation

- libs/providers/multi-provider-web/package.json
Fixes a typo in the original package that imports an invalid version of the `@openfeature/web-sdk`
> fix: correct multi-provider-web dependency

- libs/providers/go-feature-flag/src/lib/data-collector-hook.ts
The CI in PR #947 had no issue in CI, but it failed during the [release-please job](https://github.com/open-feature/js-sdk-contrib/actions/runs/9675435875/job/26692945884).
I am not sure why those checks are different, I guess we have something different in the CI.
This PR should fix the release please process for the go-feature-flag-provider.
@toddbaert @beeme1mr I am not sure if we have to update the release please file to be sure the right version is released?
> fix(gofeatureflag): remove NodeJS.timeout because it fails eslint

- libs/providers/ofrep-web/src/lib/model/in-memory-cache.ts
- libs/providers/ofrep-web/src/lib/ofrep-web-provider.ts
This class is likely to be extended, so I've made some changes to improve the QoL around that.
- resolvers now accept all params
- public access to a copy of the flag cache
> feat!: resolver signatures changes for easier overrides, cache exposure

- libs/providers/go-feature-flag-web/src/lib/go-feature-flag-web-provider.spec.ts
- libs/providers/go-feature-flag-web/src/lib/go-feature-flag-web-provider.ts
We had an issue when adding the `apiKey` as `Authorization` header.
This PR is fixing the problem and adding a test to avoid it in the future.
Fixes #1029
> fix(go-feature-flag-web): Set API Key in headers

- .github/component_owners.yml
- Adds @adams85 (ConfigCat) to the component owner's list of the ConfigCat providers. The intention behind this is that we (ConfigCat) would like to mark the providers in this repo as the official OpenFeature JS providers for ConfigCat, and we would like to participate in their development and maintenance.
I noticed that the `config-cat-web` provider wasn't on the list, so I added it. Please let me know if there was a specific reason not to list it, and I'll remove it from this PR.
> ci: add adams85 from ConfigCat as component owner

- libs/providers/growthbook-client/project.json
- tools/workspace-plugin/src/generators/open-feature/index.ts
This adds the `updateBuildableProjectDepsInPackageJson` to the growthbook provider, which fixes a bug by allowing NX to automatically generate deps based on usage. It also fixes the root cause of this missing in our template generators.
Fixes: https://github.com/open-feature/js-sdk-contrib/issues/1032
You can see the difference in the bundled output in these screenshots (before/after):
> fix: missing lodash dep (and tooling fix)

- libs/providers/config-cat-web/package-lock.json
- libs/providers/config-cat-web/package.json
Yet another [security vulnerability](https://github.com/advisories/GHSA-8hc4-vh64-cxmj) has been discovered in `axios`, so a [new version](https://github.com/configcat/js-ssr-sdk/releases/tag/v8.4.2) of `configcat-js-ssr` was released, referencing the patched version of `axios`.
This PR updates the `configcat-js-ssr` dependency of the `config-cat-web` provider to the new version.
> fix(config-cat-web): Update dependency configcat-js-ssr to v8.4.2

- libs/shared/flagd-core/src/lib/targeting/fractional.ts
- libs/shared/flagd-core/src/lib/targeting/targeting.spec.ts
- improve targeting key check in fractional operator
The old logic was always truthy. This corrects the behavior and brings it in line with Java.
https://github.com/open-feature/java-sdk-contrib/blob/main/providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/targeting/Fractional.java#L43
Run the jest test suite. The test added this PR failed before the fix.
> fix(flagd): improve targeting key check in fractional operator

- libs/providers/config-cat-web/README.md
There are a few invalid code examples in the readme of `config-cat-web`. This PR fixes them.
> fix(config-cat-web): Fix code examples in README.md

- libs/providers/flipt-web/README.md
- Adds missing `-provider` suffix in the import statement for `FliptWebProvider` in the documentation
This change ensures consistency with the actual package name and prevents potential confusion for users trying to import the package.
> docs: fix README.md for flipt-web provider

- libs/providers/launchdarkly-client/src/lib/launchdarkly-client-provider.spec.ts
- libs/providers/launchdarkly-client/src/lib/launchdarkly-client-provider.ts
- libs/providers/launchdarkly-client/src/lib/launchdarkly-provider-options.ts
Add a new option to the LaunchDarkly provider constructor, `initializationTimeout`, which lets users optionally configure the timeout used in the LDClient `waitForInitialization` method. This timeout is critical because it otherwise would cause the LDClient to hang indefinitely in cases where the network connection cannot be established.
> feat: Accept timeout for LD waitForInitialization

- libs/providers/multi-provider-web/package.json
- libs/providers/multi-provider-web/src/lib/hook-executor.ts
- libs/providers/multi-provider-web/src/lib/multi-provider-web.spec.ts
- libs/providers/multi-provider-web/src/lib/multi-provider-web.ts
- libs/providers/multi-provider/package.json
- libs/providers/multi-provider/src/lib/hook-executor.ts
- libs/providers/multi-provider/src/lib/multi-provider.spec.ts
- libs/providers/multi-provider/src/lib/multi-provider.ts
- libs/providers/ofrep-web/package.json
- libs/providers/ofrep-web/src/lib/ofrep-web-provider.ts
- package-lock.json
- package.json
- tools/workspace-plugin/src/generators/open-feature/files/hook/client/src/lib/__libFileName__.ts__tmpl__
- tools/workspace-plugin/src/generators/open-feature/files/hook/server/src/lib/__libFileName__.ts__tmpl__
- tools/workspace-plugin/src/generators/open-feature/index.ts
- updates the SDKs, particularly important for the recent breaking mentioned [here](https://github.com/open-feature/js-sdk/releases/tag/web-sdk-v1.4.0) (only the multiproviders are impacted)
- updates generator templates
cc @ajwootto @emmawillis
> chore: update sdks, absorb changes

- .gitmodules
- renovate.json
We do have a default OpenFeature Renovate configuration within our community-tooling repository. (https://github.com/open-feature/community-tooling/blob/main/renovate.json)
To reduce maintenance efforts, we should stick to the general one as a basis.
> build(renovate): Utilize default OpenFeature Renovate configuration

- .gitmodules
- libs/shared/flagd-core/package.json
- libs/shared/flagd-core/src/lib/feature-flag.spec.ts
- libs/shared/flagd-core/src/lib/feature-flag.ts
- libs/shared/flagd-core/src/lib/flagd-core.spec.ts
- libs/shared/flagd-core/src/lib/flagd-core.ts
- libs/shared/flagd-core/src/lib/parser.spec.ts
- libs/shared/flagd-core/src/lib/parser.ts
- libs/shared/flagd-core/src/lib/storage.spec.ts
- libs/shared/flagd-core/src/lib/storage.ts
- libs/shared/flagd-core/src/lib/targeting/common.ts
- libs/shared/flagd-core/src/lib/targeting/fractional.ts
- libs/shared/flagd-core/src/lib/targeting/sem-ver.ts
- libs/shared/flagd-core/src/lib/targeting/string-comp.ts
- libs/shared/flagd-core/src/lib/targeting/targeting.spec.ts
- libs/shared/flagd-core/src/lib/targeting/targeting.ts
- package-lock.json
- package.json
- release-please-config.json
- improve evaluation performance by preloading the config into JSON Logic Engine
- bumped json logic engine version
- return evaluation details instead of throwing
- converted all logs to debug
- add flag metadata
Pre-req for #1115
It should be released as v1.
- Use in the flagd playground app
- Using the the flagd JS providers
- There are Jest unit tests
> feat!: improve eval performance, restructure lib, support flag metadata

- libs/providers/go-feature-flag-web/src/lib/controller/goff-api.spec.ts
- libs/providers/go-feature-flag-web/src/lib/controller/goff-api.ts
- Behavior: web provider instances with paths in the endpoint will not have paths included in data collector calls
- Change: Match pathname logic in main web provider for data collector: https://github.com/open-feature/js-sdk-contrib/blob/main/libs/providers/go-feature-flag-web/src/lib/go-feature-flag-web-provider.ts#L95
- Instantiate web provider with endpoint like `https://some.website/examplepath`
- Check data collector calls go to `https://some.website/examplepath/v1/data/collector`
> fix(go-feature-flag): Support endpoint paths in data collector goff-api.ts

- libs/providers/flagd/README.md
- libs/providers/flagd/src/lib/configuration.spec.ts
- libs/providers/flagd/src/lib/configuration.ts
- libs/providers/flagd/src/lib/service/grpc/grpc-service.ts
- libs/providers/flagd/src/lib/service/in-process/grpc/grpc-fetch.spec.ts
- libs/providers/flagd/src/lib/service/in-process/grpc/grpc-fetch.ts
To provide a :authority header to request route to target backend services using default_authority parameter by the JS clients. This enable better integration with service proxies like Envoy, facilitating more flexible and robust gRPC client configurations.
https://github.com/open-feature/js-sdk-contrib/issues/1187
https://github.com/open-feature/flagd/issues/1532
Use defaultAuthority parameter to pass down the target authority when sending a grpc request from client side.
> feat: support proxy routing via gRPC default_authority

- .eslintrc.json
- libs/shared/ofrep-core/package.json
Fixes an issue where our auto dependency inclusion was a bit overactive and includes a mock server (msw) as a real dep.
This was because msw was used for a mock/test server which exists in not in a `.spec` or `.test` file, but in a `test/` dir.
I've updated the dependency analysis rules accordingly and this is no longer flagged to be added.
> fix: improper inclusion of test deps

- libs/providers/flagd/package.json
Address a lint issue: https://github.com/open-feature/js-sdk-contrib/actions/runs/13907544265/job/38914010257?pr=1221
> chore: add 1.13.0 as a valid grpc-js peer version

- libs/providers/flipt-web/package-lock.json
- libs/providers/flipt-web/package.json
- libs/providers/flipt-web/src/lib/flipt-web-provider.spec.ts
- package-lock.json
- package.json
Should fix tests in [#1127](https://github.com/open-feature/js-sdk-contrib/pull/1127/)
Fixes #1234523
> chore: add targeting key to flipt web tests

- .github/workflows/ci.yml
- package.json
- project.json
- tools/workspace-plugin/src/generators/open-feature/index.ts
This PR fix wrong path generation in freshly created provider after `npm run generate-provider` command
Running `test` and `lint` commands on a freshly generated provider ( by using `npm run generate-provider`) throws errors  which makes harder starting contribution on the project
Steps to reproduce: 
- Run `npm run generate-provider` and create a new `example` provider
- Launch `npx nx run example:lint` and you will get ` NX   Failed to load config "../.eslintrc.json" to extend from.` error
- Launch `npx nx run example:test` and you will get  ` NX   Can't find a root directory while resolving a config file path.` error
Repeat all steps and you will be able to run lint and test command on a freshly created provider
> fix(generator): update generated path  `project.json`, `jest.config.ts`, `.eslintrc.json`

- .release-please-manifest.json
- CODEOWNERS
- libs/providers/config-cat-web/CHANGELOG.md
- libs/providers/config-cat-web/package-lock.json
- libs/providers/config-cat-web/package.json
- libs/providers/config-cat-web/src/lib/config-cat-web-provider.spec.ts
- libs/providers/config-cat-web/src/lib/config-cat-web-provider.ts
- libs/providers/config-cat/CHANGELOG.md
- libs/providers/config-cat/package-lock.json
- libs/providers/config-cat/package.json
- libs/providers/config-cat/src/lib/config-cat-provider.spec.ts
- libs/providers/config-cat/src/lib/config-cat-provider.ts
- libs/providers/flipt-web/README.md
- libs/providers/flipt-web/package-lock.json
- libs/providers/flipt-web/package.json
- libs/providers/flipt-web/project.json
- libs/providers/flipt-web/src/lib/flipt-web-provider.spec.ts
- libs/providers/flipt-web/src/lib/flipt-web-provider.ts
- package-lock.json
- package.json
Closes: #1172
This updates the underlying Flipt Browser SDK to use our new 'isometric' JS SDK which supports both Node and Browser envs.
https://www.npmjs.com/package/@flipt-io/flipt-client-js
The older browser only sdk has been deprecated
> chore(flipt): swap underlying flipt web sdk

- libs/providers/go-feature-flag/src/lib/controller/cache.ts
- libs/providers/go-feature-flag/src/lib/model.ts
Resolves #1283
We want to be able to provide our own caching library when using the Server SDK. Adding the `cache` property to GoFeatureFlagProviderOptions.
> feat(gofeatureflag): added cache option

- libs/providers/flipt-web/src/index.ts
- libs/providers/flipt-web/src/lib/models.ts
Updates the types of the `flipt-web` provider to match the [types of the flipt client](https://github.com/flipt-io/flipt-client-sdks/blob/main/flipt-client-js/src/core/types.ts#L50-L62).
Also the types are now exported from the package.
No functional changes.
> feat(flipt-web): update types to match flipt-client-js

- libs/shared/ofrep-core/src/lib/api/errors.ts
- libs/shared/ofrep-core/src/lib/api/ofrep-api.ts
Current implementation does not include any error details when failing in 401, 403 or 429.
> feat(ofrep): adding error details for 401, 403 and 429

- libs/providers/aws-ssm/src/lib/aws-ssm-provider.spec.ts
- libs/providers/aws-ssm/src/lib/cache.spec.ts
- libs/providers/aws-ssm/src/lib/ssm-service.spec.ts
Improves the readability and maintainability of AWS SSM provider test files by standardizing their structure.
No related issues.
- Simplified test organization by removing unnecessary nested describe blocks
- Restructured `cache.spec.ts`
- Restructured `aws-ssm-provider.spec.ts` 
- Restructured `ssm-service.spec.ts`
All existing tests should continue to pass with the same coverage. The refactoring only improved structure and readability without changing test logic or assertions.
> refactor(`aws-ssm`): improve unit tests readability

- libs/providers/flagsmith/README.md
- libs/providers/flagsmith/src/lib/flagsmith-provider.spec.ts
- libs/providers/flagsmith/src/lib/flagsmith-provider.ts
While sanity check the provider after first release, this fixes the unresolvable export of the provider.
Besides that - locally tested - all functionalities work as expected.
- Changed `export default class` to `export class FlagsmithOpenFeatureProvider` -> index file doesn't re-export default
- Updated README examples to use named imports
- Exported `FlagsmithProviderConfig` interface
Follow the Readme steps
> fix: named export provider
