open-feature/js-sdk-contrib

- libs/hooks/open-telemetry/src/lib/open-telemetry-hook.ts
> feat: new feature

- .github/workflows/release-please.yml
- .release-please-manifest.json
- libs/hooks/open-telemetry/package.json
- libs/hooks/open-telemetry/project.json
- package.json
- release-please-config.json
> Add release-please

- libs/hooks/open-telemetry/src/lib/open-telemetry-hook.ts
> feat: add minor change

- libs/providers/stub/src/lib/stub-provider.ts
> fix: a fix

- .github/workflows/lint-pr.yml
- .github/workflows/release-please.yml
- .release-please-manifest.json
- README.md
- libs/hooks/open-telemetry/package.json
- libs/hooks/open-telemetry/project.json
- package.json
- release-please-config.json
- tools/generators/open-feature/index.ts
> Add release-plz

- .github/workflows/release-please.yml
- package.json
I was using "build" which happened to exist in OTel, but isn't actually the right target.
> chore: Use package, not build

- libs/hooks/open-telemetry/package.json
- libs/providers/go-feature-flag/package.json
- tools/generators/open-feature/index.ts
> fix: shell scripts in templates

- libs/hooks/open-telemetry/src/lib/open-telemetry-hook.spec.ts
> fix: change test name

- libs/providers/flagd/src/lib/flagd-provider.spec.ts
- libs/providers/flagd/src/lib/flagd-provider.ts
- libs/providers/flagd/src/lib/service/grpc/service.ts
- libs/providers/flagd/src/lib/service/http/service.ts
Signed-off-by: Michael Beemer <michael.beemer@dynatrace.com>
> feat: update flagd provider to use float api

- libs/providers/flagd/README.md
- libs/providers/flagd/src/lib/flagd-provider.spec.ts
- libs/providers/flagd/src/lib/flagd-provider.ts
Signed-off-by: Michael Beemer <michael.beemer@dynatrace.com>
> feat: change flagD default port to 8013

- README.md
Signed-off-by: Michael Beemer <michael.beemer@dynatrace.com>
> chore: fix reference to license

- release-please-config.json
- tools/generators/open-feature/index.ts
Fix release plz config (won't have any impact on 1.0.0+ libs, but will at least make things look more sensible). Also updated template.
> chore: Update release plz config

- libs/providers/go-feature-flag/src/lib/context-transfomer.spec.ts
- libs/providers/go-feature-flag/src/lib/context-transformer.ts
- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.spec.ts
- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.ts
- libs/providers/go-feature-flag/src/lib/model.ts
> refactor: update go feature flag provider to use not deprecated context transformer

- libs/hooks/open-telemetry/package.json
- libs/providers/flagd/package.json
- libs/providers/go-feature-flag/package.json
> fix!: set openfeature sdk min version to 0.2.0

- .release-please-manifest.json
> chore: remove alpha suffix

- tools/generators/open-feature/files/provider/src/lib/__libFileName__.ts__tmpl__
> chore: update provider template

- libs/providers/flagd/README.md
- libs/providers/flagd/src/lib/configuration.spec.ts
- libs/providers/flagd/src/lib/configuration.ts
- libs/providers/flagd/src/lib/flagd-provider.spec.ts
- libs/providers/flagd/src/lib/flagd-provider.ts
- libs/providers/flagd/src/lib/service/grpc/protocol.ts
- libs/providers/flagd/src/lib/service/grpc/service.ts
> feat!: add support for environment variables

- libs/hooks/README.md
- libs/hooks/open-telemetry/README.md
- libs/providers/README.md
- tools/generators/open-feature/files/hook/README.md__tmpl__
- tools/generators/open-feature/files/provider/README.md__tmpl__
> chore: change node -> js in readmes

- libs/providers/flagd/src/lib/flagd-provider.spec.ts
- libs/providers/flagd/src/lib/flagd-provider.ts
- libs/providers/flagd/src/lib/service/grpc/service.ts
- libs/providers/flagd/src/lib/service/service.ts
- implement error mapping of GRPC errors to OpenFeature SDK errors
- handle `undefined` keys in context
- add logging
> fix: improved errors, handle undefined context props

- CONTRIBUTING.md
- tools/tsconfig.tools.json
Update contributing, including requirements, and and compilation target.
> chore: update CONTRIBUTING

- libs/hooks/open-telemetry/package.json
- libs/providers/flagd-web/package.json
- libs/providers/flagd/package.json
- libs/providers/go-feature-flag/package.json
> fix: correct dependencies

- CONTRIBUTING.md
- README.md
- Updates the title
- Updates the link to the JS repo
- Removes outdated badges
- Moves the release content
> docs: improve readme

- .github/ISSUE_TEMPLATE/add-hook.md
- .github/ISSUE_TEMPLATE/add-provider.md
> chore: update github issue templates

- .release-please-manifest.json
- libs/providers/env-var/.babelrc
- libs/providers/env-var/.eslintrc.json
- libs/providers/env-var/README.md
- libs/providers/env-var/babel.config.json
- libs/providers/env-var/jest.config.ts
- libs/providers/env-var/package.json
- libs/providers/env-var/project.json
- libs/providers/env-var/src/index.ts
- libs/providers/env-var/src/lib/constant-case.spec.ts
- libs/providers/env-var/src/lib/constant-case.ts
- libs/providers/env-var/src/lib/env-var-provider.spec.ts
- libs/providers/env-var/src/lib/env-var-provider.ts
- libs/providers/env-var/tsconfig.json
- libs/providers/env-var/tsconfig.lib.json
- libs/providers/env-var/tsconfig.spec.json
- release-please-config.json
- tsconfig.base.json
- workspace.json
- adds a basic environment variable provider
This provider is intended to be used in the playground and in some updated getting started documentation.
> feat: initial environment variable provider

- release-please-config.json
- configure release please to open separate release PRs
Creates separate pull requests for each package instead of a single manifest release pull request.
> ci: configure release please to open separate release PRs

- libs/providers/flagd-web/src/lib/flagd-web-provider.spec.ts
- libs/providers/flagd-web/src/lib/flagd-web-provider.ts
Fixes a regression in reconnecting.
> fix: reconnect, tests

- libs/providers/flagd-web/src/lib/flagd-web-provider.spec.ts
- libs/providers/flagd-web/src/lib/flagd-web-provider.ts
Always use the most up-to-date context, not one cached by the function closure.
> fix: issue where context updates somtimes missed

- libs/providers/flagd-web/src/lib/flagd-web-provider.ts
- package-lock.json
- package.json
Uses the new bundled event emitter.
> feat: use new event emitter

- libs/providers/go-feature-flag/src/lib/errors/unauthorized.ts
Doing this to fix a comment, and also re-release after the nx fix.
> fix: comment typo

- libs/providers/flagd/src/lib/flagd-provider.spec.ts
- libs/providers/flagd/src/lib/service/grpc/service.ts
- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.ts
- introduce logic for zero value handling
- unit tests
Fixes #165
> fix: handling zero value responses (previously undefined)

- .release-please-manifest.json
- libs/providers/config-cat/.eslintrc.json
- libs/providers/config-cat/README.md
- libs/providers/config-cat/babel.config.json
- libs/providers/config-cat/jest.config.ts
- libs/providers/config-cat/package.json
- libs/providers/config-cat/project.json
- libs/providers/config-cat/src/index.ts
- libs/providers/config-cat/src/lib/config-cat-provider.spec.ts
- libs/providers/config-cat/src/lib/config-cat-provider.ts
- libs/providers/config-cat/src/lib/context-transformer.spec.ts
- libs/providers/config-cat/src/lib/context-transformer.ts
- libs/providers/config-cat/tsconfig.json
- libs/providers/config-cat/tsconfig.lib.json
- libs/providers/config-cat/tsconfig.spec.json
- package-lock.json
- package.json
- release-please-config.json
- tsconfig.base.json
Implements a provider for [ConfigCat](https://configcat.com).
Fixes #327.
> feat: add ConfigCat provider #327

- package.json
> chore: add lint script

- libs/providers/flagd/package.json
* fixed an issue where version conflicts could cause a TypeError to be thrown when connecting
Thanks @dyladan
> fix: failure to create grpc credentials

- libs/providers/flagd-web/src/lib/flagd-web-provider.spec.ts
- libs/providers/flagd-web/src/lib/flagd-web-provider.ts
Absorbs buf changes for remote generation.
> chore: migrate buf

- libs/providers/config-cat/src/lib/config-cat-provider.spec.ts
- libs/providers/config-cat/src/lib/config-cat-provider.ts
Adds status flag to configcat provider.
Fixes #488
> fix(config-cat): add status flag to provider

- libs/providers/flagd-web/package.json
- libs/providers/launchdarkly-client/package.json
Require first non-experimental web-sdk.
> chore!: update required web-sdk peer

- libs/providers/go-feature-flag/src/lib/data-collector-hook.ts
- Missing check in the web provider
- default field had a wrong value for errors.
> fix: GOFF fix issues in hook

- libs/providers/flagd/package.json
absorb fix in: https://github.com/open-feature/js-sdk-contrib/pull/671
> fix: "in" op error, update core

- libs/providers/flagd/src/lib/service/in-process/in-process-service.ts
- libs/shared/flagd-core/src/lib/flagd-core.ts
- libs/shared/flagd-core/src/lib/parser.ts
- libs/shared/flagd-core/src/lib/storage.ts
- libs/shared/flagd-core/src/lib/targeting/fractional.ts
- libs/shared/flagd-core/src/lib/targeting/sem-ver.ts
- libs/shared/flagd-core/src/lib/targeting/string-comp.ts
- libs/shared/flagd-core/src/lib/targeting/targeting.spec.ts
- libs/shared/flagd-core/src/lib/targeting/targeting.ts
- release-please-config.json
- improved flagd core logger
- properly handled flag configuration parsing errors
- added helper functions
The release please node workspace plugin was added so monorepo dependencies can be properly tracked.
> chore: improve logger, parsing and add helpers

- libs/shared/flagd-core/src/lib/feature-flag.ts
- libs/shared/flagd-core/tsconfig.lib.json
- libs/shared/flagd-core/tsconfig.spec.json
Signed-off-by: Michael Beemer <michael.beemer@dynatrace.com>
> fix: re-add browser support

- libs/providers/flagd/README.md
- libs/providers/flagd/package.json
- libs/providers/flagd/src/lib/configuration.spec.ts
- libs/providers/flagd/src/lib/configuration.ts
- package-lock.json
- package.json
- adds offline flag source path env
Fixes #733
> feat: add offline mode file path env

- libs/shared/ofrep-core/src/lib/api/ofrep-api.spec.ts
- libs/shared/ofrep-core/src/lib/api/ofrep-api.ts
- libs/shared/ofrep-core/src/test/handlers.ts
Implements the changes, @thomaspoignant made to the MSW handlers and adds optional auth headers to them.
I would like to already release this @thomaspoignant, as I also need your changes and some additional ones.
The original changes have been made here #776
> chore(ofrep): add more errors to msw tests

- .release-please-manifest.json
- libs/shared/ofrep-core/package.json
Bum ofrep-core to 0.1.0 before release.
> feat(ofrep): release ofrep core as 0.1.0-experimental

- libs/providers/ofrep-web/README.md
fix: typo in the OFREP web readme
> fix: typo in the OFREP web readme

- libs/shared/ofrep-core/src/lib/api/ofrep-api.ts
- libs/shared/ofrep-core/src/test/handlers.ts
-  fixes an issue where OFREP does not send content type headers
> fix: fixes an issue where OFREP does not send content type headers

- package-lock.json
- package.json
- bump OpenFeature core version
- regenerate package lock
Fixes peer dependency issues found: https://github.com/open-feature/js-sdk-contrib/pull/898
> chore: bump openfeature core version

- package-lock.json
- package.json
See https://github.com/TotalTechGeek/json-logic-engine/pull/32 and https://github.com/open-feature/flagd-schemas/pull/142
> fix: update json logic engine and schema

- libs/providers/flagd/docker-compose.yaml
- libs/providers/flagd/src/e2e/step-definitions/flagd-json-evaluator.spec.ts
- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.spec.ts
- libs/providers/launchdarkly-client/src/lib/launchdarkly-client-provider.spec.ts
- package-lock.json
- package.json
Fixes a few issues in testing.
> chore: loosen some test assertions, fix e2e matcher

- libs/providers/ofrep-web/src/lib/ofrep-web-provider.ts
- libs/shared/ofrep-core/src/lib/provider/ofrep-provider-options.ts
Removes some validation that prevents use of relative baseUrls, adds doc.
> feat: support relative baseUrls

- .release-please-manifest.json
- release-please-config.json
Configures Release Please to manage the release of the multi-provider web.
> chore: configure release please for the multi provider web

- libs/providers/go-feature-flag/src/lib/controller/goff-api.ts
- libs/providers/go-feature-flag/src/lib/go-feature-flag-provider.spec.ts
Fix an error when receiving an empty string for errorCode.
> fix(gofeatureflag): Error when receiving an empty string errorCode

- .github/workflows/ci.yml
- libs/providers/flagd/src/e2e/step-definitions/flagd-json-evaluator.spec.ts
This should fix the hung e2e testing.
> chore: fix e2e test

- .github/workflows/ci.yml
- libs/providers/flagd/docker-compose.yaml
- libs/providers/flagd/src/e2e/step-definitions/flagd-json-evaluator.spec.ts
Fixes a bad binding which was adding quotes to the targeting key.
> chore: fix fractional tests

- libs/providers/env-var/src/lib/env-var-provider.ts
- sets `runsOn` property to `server`
> fix(env-var): set runs on property to server

- libs/providers/flagsmith-client/README.md
Minor README tweak to show how to actually use targeting key and traits.
> docs(flagsmith): Show example traits and targeting key

- libs/providers/config-cat-web/README.md
- libs/providers/config-cat/README.md
A few corrections to ConfigCat providers' README.md
n/a
n/a
n/a
n/a
> docs: A few corrections to ConfigCat providers' README.md

- libs/providers/ofrep-web/README.md
In #898 not all places were updated. This PR addresses other places
> chore: fix readme examples

- libs/providers/flipt/README.md
- update flipt-io peer dependency name
> docs: update flipt-io peer dependency

- libs/providers/flipt/src/lib/flipt-provider.spec.ts
- libs/providers/flipt/src/lib/flipt-provider.ts
Resolve the issue with the returning correct default value
Fixes flipt-io/flipt/issues/3418
> fix(flipt): return the correct default value when provided in Flipt

- libs/providers/flipt-web/package-lock.json
- libs/providers/flipt-web/package.json
- libs/providers/flipt-web/src/lib/flipt-web-provider.ts
- package-lock.json
- package.json
Upgrades flipt-client-browser dependency in flipt-web provider to latest version
Re: #1066
> chore: upgrade flipt-client-browser dep

- .github/workflows/ci.yml
- adds Node 22 to the test matrix
> chore: add node 22 to test matrix

- libs/providers/ofrep-web/package.json
- libs/providers/ofrep/package.json
- release-please-config.json
> chore: update ofrep peer

- libs/providers/launchdarkly-client/README.md
- Fixes typo in launch darkly README.md
Check README.md for launchdarkly-client
> fix(launchdarkly-client--README.md): fix typo - options -> ldOptions

- libs/providers/config-cat-web/package.json
- libs/providers/config-cat/package.json
- libs/shared/config-cat-core/README.md
- package-lock.json
> fix: regenerate the package.json lockfile

- .release-please-manifest.json
- libs/providers/config-cat-web/CHANGELOG.md
- libs/providers/config-cat-web/package-lock.json
- libs/providers/config-cat-web/package.json
Reverts open-feature/js-sdk-contrib#1384
> chore: Revert "chore(main): release config-cat-web-provider 0.2.0"

- .github/workflows/ci.yml
- .github/workflows/release-please.yml
> fix: nx affected
